#
# database container
services:

  # database container
  droneiak-db:
    image: mongo:4.4
    restart: always
    container_name: droneiak-db
    environment:
      MONGO_INITDB_ROOT_USERNAME: root
      MONGO_INITDB_ROOT_PASSWORD: password
    ports:
      - '27017:27017'

  # backend container
  backend:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: droneiak-backend
    ports:
      - "8080:8080"
    depends_on:
      - droneiak-db
    environment:
      DATABASE_URL: mongodb://droneia-db:27017/droneiak-db
      DATABASE_NAME: droneiak-db
      DATABASE_USER: root
      DATABASE_PASSWORD: P@ssw0rd

  # for dev - database admin ui
  mongo-express:
    depends_on:
      - droneiak-db
    image: mongo-express
    restart: always
    container_name: mongo-express
    environment:
      ME_CONFIG_MONGODB_ADMINUSERNAME: root
      ME_CONFIG_MONGODB_ADMINPASSWORD: password
      ME_CONFIG_MONGODB_URL: mongodb://root:password@droneia-db:27017/
      ME_CONFIG_BASICAUTH: false
    ports:
      - '8081:8081'
