#
# database container
services:
  droneia-db:
    image: mongo:4.4
    restart: always
    container_name: droneiak-db
    environment:
      MONGO_INITDB_ROOT_USERNAME: root
      MONGO_INITDB_ROOT_PASSWORD: example
    ports:
      - '27017:27017'

  mongo-express:
    depends_on:
      - droneia-db
    image: mongo-express
    restart: always
    container_name: mongo-express
    environment:
      ME_CONFIG_MONGODB_ADMINUSERNAME: root
      ME_CONFIG_MONGODB_ADMINPASSWORD: example
      ME_CONFIG_MONGODB_URL: mongodb://root:example@droneia-db:27017/
      ME_CONFIG_BASICAUTH: false
    ports:
      - '8081:8081'
