spring:
  application:
    name: droneiak-app
  webflux:
    base-path: /elmenus
    problemdetails:
      enabled: true
  data:
    mongodb:
      host: localhost
      username: root
      password: password
      database: droneiak-db
      authentication-database: admin
  mvc:
    log-request-details: true
    log-resolved-exception: true
  servlet:
    multipart:
      enabled: true
      max-file-size: 10MB
      max-request-size: 10MB

# awslocal
aws:
  access-key: test
  secret-key: test
  region: eu-west-1
  s3-bucket-name: my-test-bucket
  multipart-min-part-size: 52428800 # 50MB
  awslocal-url: http://localhost:4566/

# self signed ssl
server:
  ssl:
    enabled: true
    key-alias: local_ssl
    key-store: classpath:local-ssl.p12
    key-password: password
    key-store-password: password

logging:
  level:
    web: debug
    org:
      springframework:
        web: DEBUG
jwt:
  signing:
    key: secret-key